import type { ComponentType } from "react";
import { BudgetPlanner } from "@/components/calculators/BudgetPlanner";
import { SavingsGoals } from "@/components/calculators/SavingsGoals";
import {
  CompoundInterestCalculator,
  CreditCardCalculator,
  EmergencyFundCalculator,
  EmployerContributionsCalculator,
  FeeDragCalculator,
  GstCalculator,
  HecsCalculator,
  IncomeTaxCalculator,
  InflationCalculator,
  InsuranceNeedsCalculator,
  InvestmentReturnsCalculator,
  LoanComparisonCalculator,
  MortgageCalculator,
  NetWorthTracker,
  OffsetVsRedrawCalculator,
  PaydayLoanCalculator,
  PersonalLoanCalculator,
  RefinanceBreakEvenCalculator,
  RentVsBuyCalculator,
  RetirementPlanner,
  ReverseMortgageCalculator,
  SimpleMoneyManager,
  SuperCalculator,
} from "@/components/calculators/AllTools";
import {
  AccountBasedPensionCalculator,
  InterestOnlyMortgageCalculator,
  LifeClaimsComparisonTool,
  SuperContributionsOptimiser,
  SuperPensionAgeCalculator,
} from "@/components/calculators/ExtraTools";

export const toolComponents: Record<string, ComponentType> = {
  "budget-planner": BudgetPlanner,
  "savings-goals": SavingsGoals,
  "income-tax": IncomeTaxCalculator,
  "compound-interest": CompoundInterestCalculator,
  gst: GstCalculator,
  "simple-money-manager": SimpleMoneyManager,
  mortgage: MortgageCalculator,
  "personal-loan": PersonalLoanCalculator,
  "credit-card": CreditCardCalculator,
  "payday-loan": PaydayLoanCalculator,
  "retirement-planner": RetirementPlanner,
  super: SuperCalculator,
  "employer-contributions": EmployerContributionsCalculator,
  "reverse-mortgage": ReverseMortgageCalculator,
  "loan-comparison": LoanComparisonCalculator,
  "offset-vs-redraw": OffsetVsRedrawCalculator,
  "investment-returns": InvestmentReturnsCalculator,
  "fee-drag": FeeDragCalculator,
  "insurance-needs": InsuranceNeedsCalculator,
  "emergency-fund": EmergencyFundCalculator,
  "rent-vs-buy": RentVsBuyCalculator,
  hecs: HecsCalculator,
  "net-worth": NetWorthTracker,
  inflation: InflationCalculator,
  "refinance-break-even": RefinanceBreakEvenCalculator,
  "interest-only-mortgage": InterestOnlyMortgageCalculator,
  "super-contributions-optimiser": SuperContributionsOptimiser,
  "super-pension-age": SuperPensionAgeCalculator,
  "account-based-pension": AccountBasedPensionCalculator,
  "life-claims-comparison": LifeClaimsComparisonTool,
};
